# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f46a1e5d7bfeed3fd7541dd203ec4a8cd9533a946ce7ae26463c970aa2e939d7660c805e70e8c5a6db84d9c1acaa5c0f5c0f594786eefabc634f926059a93e

test:
  secret_key_base: eb7b4b5561a82c2e761a81a91b40a80ce5dac5328f37f1944d430925f569d9b8db63e43ba76d2f73c0838d32a37e22c38375607b272476160b77aa7f3ad041a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
